version: '3'
services:
  postgres:
    image: postgres:latest
    hostname:
      postgres
    ports:
      - 5432:5432
    networks:
      - store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  service:
    depends_on:
      - postgres
    image: rafaeldbl/api-store
    build:
      context:
        ./../api-store
      dockerfile:
        Dockerfile
    ports:
      - 8080:8080
    networks:
      - store

networks:
  store:
    driver: bridge