version: '3'
services:
  db:
    image: postgres:latest
    hostname:
      postgres
    ports:
      - 5432:5432
    networks:
      - products
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  service:
    depends_on:
      - db
    image: rafaeldbl/api-store
    build:
      context:
        ./../api-store
      dockerfile:
        Dockerfile
    ports:
      - 8080:8080
    networks:
      - products

networks:
  products:
    driver: bridge