version: '3'
services:
  postgres:
    image: postgres:latest
    hostname:
      postgres
    ports:
      - 5432:5432
    networks:
      - store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
  service:
    depends_on:
      - postgres
    image: rafaeldbl/api-store
    build:
      context:
        ./../api-store
      dockerfile:
        Dockerfile
    ports:
      - 8080:8080
    networks:
      - store
    volumes:
      - ./maven-repo:/root/.m2

  front:
    depends_on:
      - service
    image: rafaeldbl/web-store
    build:
      context:
        ./../web-store
      dockerfile:
        Dockerfile
      args:
        ENV_CONFIG: docker
    ports:
      - 80:80
    networks:
      - store
    volumes:
    - ./data/server/logs:/usr/src/app/logs
    - ./data/server/logs/nginx:/var/log/nginx/
    - ./configs/nginx:/etc/nginx/conf.d
    - ./data/server/static/:/usr/src/app/static
    - ./data/server/uploads/:/usr/src/app/uploads

networks:
  store:
    driver: bridge
